version: 1.6.4.{build}
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore Razor.sln
build:
  project: Razor.sln
  verbosity: minimal
test: off
artifacts:
- path: bin\Win32\Release
  name: Razor-dev-preview
deploy:
- provider: GitHub
  release: Razor-dev-preview
  description: Auto-build by AppVeyor\n\nThis is built automatically after each commit to master, so it may contain bugs and/or unfinished features. Use at your own risk.\n\nOfficial releases will be listed here and given proper version numbers with release notes.
  auth_token:
    secure: 8F11pQiKmjN7rkwx4TfXay3Z3Ocj+5zpKGeXWYuK/LLGY8HCtFYoXzmGzlePwDwX
  prerelease: true
  force_update: true
skip_commits:
  message: /\[chore\]/
  files:    
    - help/
    - docs/
    - '**/*.md'
    - '**/*.ps1'
    - '**/*.yml'